# Generated by Django 5.0.7 on 2024-07-23 17:26

import playlist.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='length_in_seconds',
            field=models.IntegerField(validators=[playlist.validators.validate_music_length]),
        ),
    ]
