# Generated by Django 5.0.7 on 2024-07-23 19:09

import django.db.models.deletion
import playlist.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_alter_music_length_in_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='singer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='musics', to='playlist.singer'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='name',
            field=models.CharField(max_length=50, validators=[playlist.validators.validate_name_is_char]),
        ),
    ]
