# Generated by Django 5.0.7 on 2024-07-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_music_singer_alter_singer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='musics',
            field=models.ManyToManyField(related_name='playlists', to='playlist.music'),
        ),
    ]
